### ISSUE TITLE
UERANSIM-UES 3.2.6 not working -> DNN Problem

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#103]
Hello, so i have subscribed to imsi in the open5gs WebUI '999700000000001'. But in the ueransim-ue container appears this error. All other container logs seems fine

![Captura de ecrã de 2022-11-19 03-21-00](https://user-images.githubusercontent.com/43995498/202832099-2358b5a4-8383-4f68-9211-e453c5b2a778.png)

**Comment by DiogoCruz40** [comment]
OK, i found out the problem is in your sd it must be 0xffffff instead of 0x111111

**Comment by DiogoCruz40** [comment]
Is it possible to add a service to UERANSIM-UES? If yes how?

**Comment by DiogoCruz40** [comment]
Is it possible to redirect all traffic to the network interface uesimtun0 without using the manual command
 "ping -I uesimtun0 8.8.8.8"

**Comment by avrodriguezgrad** [comment]
Hello Diogo, thanks for using our charts. First of all,

> OK, i found out the problem is in your sd in apn it must be 0xffffff instead of 0x111111

Are you sure about this? Which version are you using of the charts? I don't see any 0xffffff in the charts. All charts have configured 0x111111.

> Is it possible to redirect all traffic to the network interface uesimtun0 without using the manual command "ping -I uesimtun0 8.8.8.8"

Automatically, I don't know if it is possible. I think changing the default route could be possible, but I've never done it. You can search in the official repo of UERANSIM: https://github.com/aligungr/UERANSIM

**Comment by DiogoCruz40** [comment]
Hello @avrodriguezgrad, thank you so much,

> Are you sure about this? Which version are you using of the charts? I don't see any 0xffffff in the charts. All charts have configured 0x111111.

Yes, I'm sure of this. I'm using your latest versions of charts. Please consider testing on an environment the UERANSIM + Open5gs. The problem is in the APN slice configuration 'sd'. As i said i solved it using the sd '0xffffff'.

> Automatically, I don't know if it is possible. I think changing the default route could be possible, but I've never done it. You can search in the official repo of UERANSIM: https://github.com/aligungr/UERANSIM

I will check it out thank you, probably i will configure the routes in your entrypoint.sh, as i configured to open the plc server.
