### ISSUE TITLE
Run the pods with Privileges

### ISSUE THREAD

**Issue by tywofxd** [Gradiant/openverso-charts#106]
Hi!
I want to run some of the NFs with Privileges. I add containerSecurityContext to AMF in the vaule.yaml while deploying the open5gs, referring the the settings of UPF, since in the created UPF pod I can use tc to inject some network faults to see the 5g core's performace. 
But in the AMF pod, I cannot use the tc command due to privileges.
After I add containerSecurityContext to give AMF the privileges, the tc command still fail.
Could you please tell me how to set the the configurations to run AMF as a previleged pod?
Thanks in advance.

**Comment by tywofxd** [comment]
Hello, I tried to find out the solution.
I set the runAsUser field of containerSecurityContext as 0 for the AMF's part in the value.yaml, and other fields referring to the UPF's setting. 
Now I can use tc in the AMF pod.

**Comment by cgiraldo** [comment]
Glad to here you solve it!

I close the issue.
