### ISSUE TITLE
Issue in Open5GS SBI

### ISSUE THREAD

**Issue by joaodonatosilva2** [Gradiant/openverso-charts#111]
Hello,

I've deployed Open5GS in kubernetes using this repository:
https://github.com/Gradiant/openverso-charts
All pods are successfully deployed but I'm getting the following for the PCF component:
![image](https://user-images.githubusercontent.com/103496863/209822412-b6006c12-fecf-4e8d-9e03-c37dc10b5807.png)

Do you have a suggestion on how to solve this issue?

Thank you very much for the attention,
Best regards,
João Silva

**Comment by cgiraldo** [comment]
Some client is requesting an HTTP 1.x to sbi endpoint while only HTTP2 is supported by open5gs.

For example, using curl as client you need to use flag `--http2-prior-knowledge`:

```
curl --http2-prior-knowledge http://open5gs-nrf-sbi:7777/nnrf-nfm/v1/nf-instances
```
