### ISSUE TITLE
Issue with SMF pod

### ISSUE THREAD

**Issue by joaodonatosilva2** [Gradiant/openverso-charts#113]
Hello,

I'm trying to deploy open5GS helm charts for 5G using this repository: https://github.com/Gradiant/openverso-charts and deploying the helms present in the folder 'openverso-charts/charts/open5gs'.
I have all the pods running with the exception of SMF, which is generating the following logs:

Open5GS daemon v2.5.6

01/04 11:39:08.987: [app] INFO: Configuration: '/opt/open5gs/etc/open5gs/smf.yaml' (../lib/app/ogs-init.c:126)
01/04 11:39:09.010: [metrics] INFO: Prometheus mhd_server() [0.0.0.0]:9090 (../lib/metrics/prometheus/context.c:320)
01/04 11:39:09.038: [diam] ERROR: pid:Main in fdderror@fdd.y:69: /opt/open5gs/etc/freeDiameter/smf.conf:266.65 : Name or service not known
 ((null):0)
01/04 11:39:09.038: [diam] ERROR: pid:Main in fdderror@fdd.y:69: /opt/open5gs/etc/freeDiameter/smf.conf:266.65 : An error occurred while parsing the configuration file
 ((null):0)
01/04 11:39:09.038: [diam] ERROR: pid:Main in fd_conf_parse@config.c:281: ERROR: in '((fddparse(fd_g_config)))' :	Invalid argument
 ((null):0)
01/04 11:39:09.038: [diam] ERROR: pid:Main in fd_core_parseconf_int@core.c:245: ERROR: in '((fd_conf_parse()))' :	Invalid argument
 ((null):0)
01/04 11:39:09.038: [diam] ERROR: pid:Main in ogs_diam_init@init.c:49: ERROR: in '(fd_core_parseconf(conffile))' :	Invalid argument
 ((null):0)
01/04 11:39:09.039: [smf] FATAL: smf_fd_init: Assertion `rv == 0' failed. (../src/smf/fd-path.c:36)
01/04 11:39:09.039: [core] FATAL: backtrace() returned 7 addresses (../lib/core/ogs-abort.c:37)
open5gs-smfd(+0x43173) [0x563bc255a173]
open5gs-smfd(+0xd42e) [0x563bc252442e]
open5gs-smfd(+0xc8c6) [0x563bc25238c6]
open5gs-smfd(+0xd140) [0x563bc2524140]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f2d356f4d0a]
open5gs-smfd(+0xc7fa) [0x563bc25237fa]
/entrypoint.sh: line 41:     7 Aborted                 (core dumped) $@

Any suggestion on how to solve this issue?

Thank you very much in advance,
Best regards,
João Silva

**Comment by cgiraldo** [comment]
smf Diameter is not able to connect to the pcrf diameter peer. 
If you have not changed the default configuration, smf diameter tries to ConnectTo "open5gs-pcrf-frdi".
In order to resolve this name, the corresponding kubernetes service must exist:

```
kubectl describe service open5gs-pcrf-frdi
```
