### ISSUE TITLE
When updating Open5GS web UI to 2.6.0 using populate the header says Open5GS 2.5.6

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#121]
![Screenshot from 2023-03-06 18-40-17](https://user-images.githubusercontent.com/43995498/223201357-02ace9be-6ef0-4fd0-89d5-ef881489b052.png)

**Comment by DiogoCruz40** [comment]
Basically i changed your [values.yaml](charts/open5gs/values.yaml) to 2.6.0 in all network functions, including the open5GS web UI. The Open5GS web UI title shows Open5GS 2.5.6 instead of Open5GS 2.6.0

**Comment by avrodriguezgrad** [comment]
Hi Diogo,

We've seen the new release of open5GS and we've updated our images repo. When the [PR](https://github.com/Gradiant/openverso-images/pull/168) is accepted, the new version (2.6.0) will be accesible to pull from dockerhub.

Thanks for telling us this!
