### ISSUE TITLE
Upgrade Open5GS to 2.6.1 version failed 

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#122]
![Screenshot from 2023-03-15 19-36-27](https://user-images.githubusercontent.com/43995498/225423623-e81fce4e-bbb8-4de0-a608-e366172264f7.png)
![Screenshot from 2023-03-15 19-35-48](https://user-images.githubusercontent.com/43995498/225423630-098a868f-ceec-42a0-a46c-af10e7b61813.png)

**Comment by avrodriguezgrad** [comment]
Which config file are you using? 

BTW, I think your issue is related with [this](https://github.com/open5gs/open5gs/issues/2058). If you are able to solve it, could you tell us the solution?

**Comment by alexagaman** [comment]
> Which config file are you using?
> 
> BTW, I think your issue is related with [this](https://github.com/open5gs/open5gs/issues/2058). If you are able to solve it, could you tell us the solution?

Yes you could say the issue is related to that, the tls configuration changed as you can see in the [commit](https://github.com/open5gs/open5gs/commit/05fbaf69587488e53b5e741a9ada9f9fa5749322) mentioned in that thread, and it needs this part in the configs to disable it:
```
sbi:
    server:
      no_tls: true
    client:
      no_tls: true
```
I tested this by editing the configmap directly, didn't find a way to fix this without changing the charts.

**Comment by avrodriguezgrad** [comment]
Hi,
I've made [changes](https://github.com/Gradiant/openverso-charts/pull/126) in 5G services charts to permit TLS config, as @alexagaman told us. I tested them, and they worked, but please, can you test the changes in your environment?

Thank you in advance.

**Comment by DiogoCruz40** [comment]
Hello, @avrodriguezgrad.
Thank you, everything is operating well. 
If it's feasible, I'd like to leave you with one last request: provide certificate configuration in the open5gs charts.

**Comment by avrodriguezgrad** [comment]
Hi, I'm glad to hear that it's working for you too. We are working on other things right now, but we'll add your request to our TODO list.

**Comment by avrodriguezgrad** [comment]
Hi Diogo,
In the past, I had a problem with mongodb too. The readiness and liveness probes waste a lot of resources, so they fail and the pod crushes. I solve it erasing from the bitnami mongodb yaml the part of readiness and liveness, or you can try to give more resources to the mongodb pod.

Nevertheless, I don't know if this is your issue with the logs you posted, but I feel it's a problem outside our scope.

**Comment by DiogoCruz40** [comment]
I turned off the probes and now it is running, but the other containers are still not running
![image](https://user-images.githubusercontent.com/43995498/231488728-6cfd0087-8004-4d8d-8a8a-fe5a0e787e2c.png)

**Comment by DiogoCruz40** [comment]
@avrodriguezgrad I rebooted the virtual machines and it started working. 
Thank you so much for your help.
