### ISSUE TITLE
Open5gs 2.6 release not included in Openverso charts

### ISSUE THREAD

**Issue by vinayakSharm** [Gradiant/openverso-charts#129]
Hello team!

I am currently working in R&D at Dish Network. We aim to build a reinforcement learning agent to scale UPF's. 

An issue we are currently facing is that PDU sessions do not transfer over from an UPF (if that UPF gets deleted or removed) to a new UPF via SMF. This is an issue in 2.4 that is patched in 2.6. 

Can Openverso please upgrade Open5gs to 2.6 to enable users with this new functionality? We would like the 2.6 version helm charts to be included as part of Openverso. 

Respectfully, Vinayak

**Comment by vinayakSharm** [comment]
Changing image number in the values.yml to pull 2.6.2 seems to work. Closing!

**Comment by avrodriguezgrad** [comment]
Hi @vinayakSharm 
It's nice to see that our work is being used to R&D, that's our main objective! 

You found the solution correctly and, also, in this [repo](https://github.com/Gradiant/openverso-images) we have a collection of images you can use. Today, it was release 2.6.4 open5gs version! 

Furthermore, if you fix something or add some new functionality, feel free to PR and we'll review it.

Thanks!
