### ISSUE TITLE
Scalability in Open5Gs Chart

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#132]
Hello there,

Is there a method for me to scale my open5gs functions, specifically UPF and SMF, so that I can handle more user equipment traffic?

**Comment by avrodriguezgrad** [comment]
Hi Diogo,

We haven't worked in that feature yet, it's something we want to research but it's not our priority at the moment.

If you are going to research in this area and find something useful, feel free to make a PR.

BR,
Álvaro

**Comment by DiogoCruz40** [comment]
Hey @avrodriguezgrad, thank you for your answer!

Does the Open5GS official community already offer scalability? And what are the main functions that i need to be looking for in order to scale the core?

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40 !

I don't know if open5gs offers scalability as a default feature, but if I was you, I would ask in its repo. 
And about the main functions, I think the important ones are AMF, SMF and UPF because they are the functions that manage UEs access and sessions.

BR,
Álvaro

**Comment by DiogoCruz40** [comment]
Hello @avrodriguezgrad, 

Thank you that's what i did!

One final question, is there a script to add UE subscribers to open5gs DB? Any sugestions?

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40 

Yes. Open5GS has a [script](https://github.com/open5gs/open5gs/blob/main/misc/db/open5gs-dbctl) and we have our own image of that [script](https://github.com/Gradiant/openverso-images/tree/main/images/open5gs-dbctl).

There is an example of how it works [here](https://github.com/Gradiant/openverso-charts/blob/master/charts/open5gs/values.yaml)

BR,
Álvaro
