### ISSUE TITLE
SCTP does not establish connections between pods on different nodes.

### ISSUE THREAD

**Issue by mandrade1stf** [Gradiant/openverso-charts#137]
I have an experiment running with Open5GS that works perfectly with Flannel; however, when I switch to Cilium, I can no longer establish a connection between the eight Ueransim pods and the AMF using SCTP. I noticed that UERANSIM and AMF work when they are on the same node, but they do not function when on different nodes.

```mermaid
flowchart TB
    subgraph node1
        direction LR
        ueransim02
        ueransim03
        ueransim04
    end
     subgraph node2
        direction LR
        ueransim05
        ueransim06
        ueransim07
        ueransim08
    end
    subgraph node3
        direction LR
        ueransim01 
        amf
    end
    ueransim01 == OK ==> amf
    ueransim02 -.-> amf
    ueransim03 -.-> amf
    ueransim04 -.-> amf
    ueransim05 -.-> amf
    ueransim06 -.-> amf
    ueransim07 -.-> amf
    ueransim08 -.-> amf
    linkStyle 1,2,3,4,5,6,7 stroke:red,color:red;
    linkStyle 0 stroke:green;

```

**Comment by cgiraldo** [comment]
From your description, It seems to be a bug related with cillium and not the open5gs chart.

I check SCTP support in cilium and It is beta, It has to be enabled when installing it. 
Check the [Cilium SCTP Limitations and warnings](https://docs.cilium.io/en/latest/configuration/sctp/) if it gives you more information.
