### ISSUE TITLE
Open5gs -CrashLoopBackOff after first installation

### ISSUE THREAD

**Issue by rodrigosanzsanz** [Gradiant/openverso-charts#139]
Hi!

I was able to install and perform data traffic test in first installation. But after this I am trying to install again and I suffer some issues and not all pods are created correctly.

After some checks I dont see the issue and I know some collegues had similar issues. Maybe you know some reason or key info.¿?

![Captura de pantalla 2023-11-10 a las 13 14 57](https://github.com/Gradiant/openverso-charts/assets/133344742/dc1eed24-e2d4-4349-aa0c-f54c2654e1f4)

On the other hand I was able to launch 3 UPFs modifying HPA to 3 as maxium. This is suppose to course traffic in any of 3 UPFs in a high availability scenario. In theory it should be possible even without modify config SMF info, but I dont know if any know something about this test.
Additionally with Rolling Update if any config change is done it should  hav no downtime.

Do you have any help for any of 2 topics? Thanks in advance!

And congrats for the doc effort.BR

**Comment by rodrigosanzsanz** [comment]
Hi,

I have solved my first problems, deleting pvcs and waiting some time before executing RAN part.
For the other topic, about traffic with several UPFs, any opinion is welcome. Thanks

**Comment by cgiraldo** [comment]
Hi,

I will not try to mix UPF pod replicas with open5gs UPF instances, at least not for initial experimentation.

If you want to experiment with multiple UPFs I recommend you install multiple UPFs charts with a single replica each.

The integration of kubernetes Design (Services as Load Balancer of ephemeral Deployment´s Pod replicas ) and the 5G Core Design ( with Network Functions and registration of NFs in NRF) are not easy. 
Maybe we can open a discussion to share advances in this direction.

Kind regards,
