### ISSUE TITLE
Set static ips for each network function via values.yaml

### ISSUE THREAD

**Issue by Stainless2k** [Gradiant/openverso-charts#145]
Hello,

we are using your Charts to do a bit of research regarding security in containerized 5G networks, using tools like [Falco](https://github.com/falcosecurity/falco). 

For convince sake, even tho its not the best practice, we would like to give each Network function an predefined static IP address in our Kubernetes Cluster.  Is this achievable via the values.yaml of the [open5gs helm chart](https://artifacthub.io/packages/helm/gradiant-openverso/open5gs) ?

**Comment by cgiraldo** [comment]
Hi,

You can try to provide a fixed clusterIP in the services of each Network function. 

For example take a look to the values of the smf: https://artifacthub.io/packages/helm/gradiant-openverso/open5gs-smf

Using the open5gs chart you can set the smf sbi IP with the `smf.services.sbi.clusterIP` value.
Or you can set the smf gtpc IP with `smf.services.gtpc.clusterIP` value.

However, just to let you know, we have not tested this kind of deployment.

Good luck!
