### ISSUE TITLE
Openverso-charts new release

### ISSUE THREAD

**Issue by anabel1012** [Gradiant/openverso-charts#146]
Hello,

We have seen that Open5Gs has released a new version of the code. Also that you have updated the images in docker hub (v2.7.0). But do you have an approximate date for the new release of the Helm?

We would really appreciate it.

Thanks in advance.
Anabel

**Comment by avrodriguezgrad** [comment]
Hi Anabel,

We're working on updating the charts and expect to release them by the end of this month.

Thanks,
Álvaro

**Comment by rodrigosanzsanz** [comment]
That sounds great! I am waiting for that too. Thanks!Let´s wait!

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 @rodrigosanzsanz 

Charts are available. Now, we upload the charts to dockerhub and they are available as oci. You can deploy it with the command `helm pull oci://registry-1.docker.io/gradiant/open5gs --version 2.2.0`

Also, we change the repository of the images from openverso to gradiant, so the new images and the support will be done for the images _gradiant/<image-name>_

If you see that something is missing, feel free to reopen the issue or create a PR explaining the changes, and we'll discuss it.

BR,
Álvaro
