### ISSUE TITLE
UDR sends 404 [imsi-999700000000001] Cannot find SUPI in DB (../src/udr/nudr-handler.c:68) even if subscriber is configured

### ISSUE THREAD

**Issue by nitinbhat** [Gradiant/openverso-charts#151]
Hi,

I have deployed open5gs and configured a subscriber with below command

`open5gs-dbctl add_ue_with_slice imsi-999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 0x111111`

Also verified the same on mongodb.

`> db.subscribers.find()
{ "_id" : ObjectId("65ae4932d9685518c5e4c37e"), "schema_version" : 1, "imsi" : "imsi-999700000000001", "msisdn" : [ ], "imeisv" : [ ], "mme_host" : [ ], "mm_realm" : [ ], "purge_flag" : [ ], "slice" : [ { "sst" : 1, "sd" : "0x111111", "default_indicator" : true, "session" : [ { "name" : "internet", "type" : 3, "qos" : { "index" : 9, "arp" : { "priority_level" : 8, "pre_emption_capability" : 1, "pre_emption_vulnerability" : 2 } }, "ambr" : { "downlink" : { "value" : 1000000000, "unit" : 0 }, "uplink" : { "value" : 1000000000, "unit" : 0 } }, "pcc_rule" : [ ], "_id" : ObjectId("65ae4932d9685518c5e4c37f") } ], "_id" : ObjectId("65ae4932d9685518c5e4c380") } ], "security" : { "k" : "465B5CE8B199B49FAA5F0A2EE238A6BC", "op" : null, "opc" : "E8ED289DEBA952E4283B54E88E6183CA", "amf" : "8000" }, "ambr" : { "downlink" : { "value" : 1000000000, "unit" : 0 }, "uplink" : { "value" : 1000000000, "unit" : 0 } }, "access_restriction_data" : 32, "network_access_mode" : 0, "subscribed_rau_tau_timer" : 12, "__v" : 0 }
>`

When a call is made, UDR sends 404

Logs on UDR

`01/22 13:03:33.372: [app] INFO: Configuration: '/opt/open5gs/etc/open5gs/udr.yaml' (../lib/app/ogs-init.c:126)
01/22 13:03:33.385: [dbi] INFO: MongoDB URI: 'mongodb://open5gs-mongodb/open5gs' (../lib/dbi/ogs-mongoc.c:130)
01/22 13:03:33.386: [sbi] INFO: NF Service [nudr-dr] (../lib/sbi/context.c:1438)
01/22 13:03:33.386: [sbi] INFO: nghttp2_server() [http://10.1.2.129]:9004 (../lib/sbi/nghttp2-server.c:395)
01/22 13:03:33.386: [app] INFO: UDR initialize...done (../src/udr/app.c:31)
01/22 13:03:33.392: [sbi] INFO: [a5a154c6-b926-41ee-a047-8bd8399c04da] NF registered [Heartbeat:10s] (../lib/sbi/nf-sm.c:214)
01/22 13:26:42.418: [dbi] INFO: [imsi-999700000000001] Cannot find IMSI in DB (../lib/dbi/subscription.c:56)
01/22 13:26:42.418: [udr] WARNING: [imsi-999700000000001] Cannot find SUPI in DB (../src/udr/nudr-handler.c:68)`

What could be issue here?

<img width="1582" alt="image" src="https://github.com/Gradiant/openverso-charts/assets/46515714/034cddaa-40d9-4a61-82a6-e1a20c25cb3a">

**Comment by avrodriguezgrad** [comment]
Hi,

I think your issue is the format of the IMSI. You've put "imsi-999700000000001" and you only need to put "999700000000001".

Try this and give me feedback if this solves your issue.

Cheers,
Álvaro

**Comment by nitinbhat** [comment]
Hi Álvaro,

Thanks for the quick response and pointing it out. Yes, this was the issue. After correcting it, I can see registration is complete.

Thanks
Nitin
