### ISSUE TITLE
Certificates of hss,mme and pcrfr pods is expired when changed tag to latest

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#34]
So i tried to change the replicasets to latest tag and in the pods it says that The certificate is expired(mme,hss and pcrf).
`
2022/01/24 13:26:22.0510: [ 1]: WARNING: mongoc: Falling back to malloc for counters.

24/1/2022 13:26:22 | Open5GS daemon v2.3.3

24/1/2022 13:26:22 | 01/24 13:26:22.514: [app] INFO: Configuration: '/opt/open5gs/etc/open5gs/pcrf.yaml' (../lib/app/ogs-init.c:129)

24/1/2022 13:26:22 | 01/24 13:26:22.518: [dbi] INFO: MongoDB URI: 'mongodb://open5gs-mongodb/open5gs' (../lib/dbi/ogs-mongoc.c:130)

24/1/2022 13:26:22 | 01/24 13:26:22.523: [diam] ERROR: pid:Main in fd_conf_parse@config.c:465: - The certificate is expired.

24/1/2022 13:26:22 | ((null):0)

24/1/2022 13:26:22 | 01/24 13:26:22.523: [diam] ERROR: pid:Main in fd_core_parseconf_int@core.c:245: ERROR: in 
'((fd_conf_parse()))' : Invalid argument

24/1/2022 13:26:22 | ((null):0)

24/1/2022 13:26:22 | 01/24 13:26:22.523: [diam] ERROR: pid:Main in ogs_diam_init@init.c:49: ERROR: in '(fd_core_parseconf(conffile))' : Invalid argument

24/1/2022 13:26:22 | ((null):0)

24/1/2022 13:26:22 | 01/24 13:26:22.625: [pcrf] FATAL: pcrf_fd_init: Assertion `rv == 0' failed. (../src/pcrf/pcrf-fd-path.c:29)

24/1/2022 13:26:22 | 01/24 13:26:22.625: [core] FATAL: backtrace() returned 7 addresses (../lib/core/ogs-abort.c:37)
24/1/2022 13:26:22 | open5gs-pcrfd(+0x67d8) [0x5649f1ca17d8]

24/1/2022 13:26:22 | open5gs-pcrfd(+0x5085) [0x5649f1ca0085]

24/1/2022 13:26:22 | open5gs-pcrfd(+0x4736) [0x5649f1c9f736]

24/1/2022 13:26:22 | open5gs-pcrfd(+0x4f0e) [0x5649f1c9ff0e]

24/1/2022 13:26:22 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f4ea0c74d0a]

24/1/2022 13:26:22 | open5gs-pcrfd(+0x466a) [0x5649f1c9f66a]

`

**Comment by cgiraldo** [comment]
You are correct, the latest tag was not updated  (it points to v2.3.3).

I have updated It to point to v2.4.0,  It must not include expired certificates now.
