### ISSUE TITLE
I can't make UE from UERANSIM work with open5gs, both openverso-charts 

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#37]
![Captura de ecrã de 2022-02-04 22-01-22](https://user-images.githubusercontent.com/43995498/152609274-0f37433d-80cc-45d0-b795-06eff769e68e.png)

So i ping for exemple google.com and it's 100% package lost
I used your configs and only changed the version to 3.2.4, 3.2.2 didn t work either.
I can't find the reason why this is not working with open5gs tag latest

Can you help plz?

**Comment by DiogoCruz40** [comment]
Any suggestion?

**Comment by cgiraldo** [comment]
Did you correctly register the UEs in the core?

**Comment by DiogoCruz40** [comment]
I'm sry there's no manual on how to do that, can you specify what i have to register?

**Comment by DiogoCruz40** [comment]
i have testing everything and i can't figure out where the interfaces are failling to proceed to public internet

**Comment by cgiraldo** [comment]
Nat should be enabled by default in upf, giving you internet connectivity to ues.
Take a look to the entrypoint.sh of the openverso/open5gs image (https://github.com/Gradiant/openverso-images/blob/main/open5gs/entrypoint.sh).

You can check there how upf containers configures NAT.

I hope that helps to debug your problem.

**Comment by DiogoCruz40** [comment]
I'm in portugal, do my mcc and mnc matter here?

**Comment by cgiraldo** [comment]
No. You are using UERANSIM so you are not actually using radio resources but simulation. 
The requirements is that MCC, MCC and TAC to be the same across UERANSIM and open5gs.
Default UERANSIM and open5gs in values.yaml are the same for this parameters:

```
MCC: 901
MNC: 70
TAC: 0001
```

So you can keep the default values and It should work.

Have you try internet access through the ue container?

**Comment by DiogoCruz40** [comment]
Yes i have tried, so for the eth0 it ping's outside ip's like 8.8.8.8, but for interfaces like uesimtun0 it's not working, 100% package loss.

**Comment by cgiraldo** [comment]
have the ue receive an IP in the uesimtun0 interface (10.45.0.X)?
have you ping to the IP of the other side of the tunel (10.45.0.1)?
have you a correct ip route entry in ue setting the gateway to the IP of the other side of the uesimtun0?

**Comment by DiogoCruz40** [comment]
> have the ue receive an IP in the uesimtun0 interface (10.45.0.X)?
Yes, both 4 ue appear but the state is unknown.
> have you ping to the IP of the other side of the tunel (10.45.0.1)?
I have tried pinging with interface of one ue, it didn't work. Then i tried ping with eth0 it didn't work.
> have you a correct ip route entry in ue setting the gateway to the IP of the other side of the uesimtun0?
I didn't understand the question, how can i do that?

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40,
How did you do the deployment of both charts? Can you tell me which commands did you execute and which files did you change?
On the other hand, which CNI do you have in your kubernetes cluster?

**Comment by DiogoCruz40** [comment]
Yes @avrodriguezgrad so first i deployed a rke2 cluster and then rancher server. In rancher server i created a namespace called open5gs where i deployed open5gs and ueransim like this:
 
Deploy of open5gs - https://github.com/Gradiant/openverso-charts

1. Install helm openebs for dynamic persistence volumes:

   $  `helm repo add openebs https://openebs.github.io/charts` 

   $  `helm repo update`

   $  `helm install openebs --namespace openebs openebs/openebs --create-namespace`

2. Install helm openverso/open5gs:

   $  `kubectl create ns open5gs` 

   $  `helm repo add openverso https://gradiant.github.io/openverso-charts/`

   $  `helm install open5gs openverso/open5gs -n open5gs`

3. Criate persistence volume claim of open5gs-mongodb-pvc with class openebs-hostpath

4. Edit web ui service to nodeport

Deploy of ueransim:

1. Install the ueransim:

   $ `helm repo add openverso https://gradiant.github.io/openverso-charts/`

   $ `helm install ueransim openverso/ueransim -n open5gs`

2. Put the same MCC and MNC on ueransim from open5gs amf and mme

The canal CNI is the default of rke2 cluster. I've deployed the multus cni on default namespace of cluster to.

**Comment by avrodriguezgrad** [comment]
@DiogoCruz40 I'm going to figure out what is happening and I'll tell you something tomorrow

**Comment by DiogoCruz40** [comment]
@avrodriguezgrad thank you so much

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40 
We discovered why the chart is failing, so next days we are going to upload a new working version. Sorry for that, I'll tell you when this new version is ready for deployment.

**Comment by DiogoCruz40** [comment]
Hello @avrodriguezgrad, thank you good sir. If you could explain why is failling to, i would appreciate it .

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40 
We've updated UERANSIM chart so right now following the steps you told us, both charts (open5gs and ueransim) are working. I attach a image to show you that UEs have connectivity.
![UEs_working](https://user-images.githubusercontent.com/91475361/155479648-131bbbac-b9da-40f2-a8d1-5020e3930739.png)

The previous UERANSIM chart was failing due to the deployment in an unique pod. Our theory is UE's default route was overwritting gNB's default route, so that was the cause of not having connectivity in UE's.

¿Can you test it and tell us if it is working for you? Remember to update the openverso repo with: helm repo update

**Comment by DiogoCruz40** [comment]
Hi @avrodriguezgrad it's working, thank you soo much. 
Another question, you deployed the UERANSIM trough statefulset, shouldn't it be through deployment as this has no state?

**Comment by avrodriguezgrad** [comment]
Hi @DiogoCruz40 

Yes, it could be an option to deploy gnb as deployment, but we follow the same pattern as in open5gs. Design decision, not matter at all. 

I'm going to close the PR. Feel free to open it again or open another if you have any problem. Greetings!
