### ISSUE TITLE
Restore data in open5gs/mongodb problem using chart open5gs

### ISSUE THREAD

**Issue by DiogoCruz40** [Gradiant/openverso-charts#38]
Hey so i find another problem with restoring data from a persistence volume, first i created a persistence volume, then i change the deployment of open5gs/mongodb storage to /mnt/bitnami/mongodb and finally i tested database with open5gs web ui. When i delete the mongodb pod it should restore the data from the persistence volume and that doesn't happen.

**Comment by cgiraldo** [comment]
Hi. We currently test the deployments using [dynamic persistent volume provisioning](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic) .
We install OpenEBS in our kubernetes cluster and set the default storageclass to `openebs-hostpath`.

However, I don't think it should be different providing an static PV.

**Comment by DiogoCruz40** [comment]
Inside mongodb logs it says: 

mongodb 16:44:24.52 INFO ==> ** Starting MongoDB setup **
--
7/2/2022 16:44:24 | mongodb 16:44:24.53 INFO ==> Validating settings in MONGODB_* env vars...
7/2/2022 16:44:24 | mongodb 16:44:24.53 WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
7/2/2022 16:44:24 | mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied

**Comment by DiogoCruz40** [comment]
Thanks i used openebs for this
