### ISSUE TITLE
SMF connection issues

### ISSUE THREAD

**Issue by s-choudhury** [Gradiant/openverso-charts#45]
When trying to connect a UE from UERANSIM, it's failing on one step which I think is related to the SMF not connecting. Below are the logs from the various NFs:

SMF (logs seem fine):
04/11 21:50:57.156: [app] INFO: Configuration: '/opt/open5gs/etc/open5gs/smf.yaml' (../lib/app/ogs-init.c:129)
04/11 21:50:57.275: [gtp] INFO: gtp_server() [10.1.59.79]:2123 (../lib/gtp/path.c:30)
04/11 21:50:57.275: [gtp] INFO: gtp_server() [10.1.59.79]:2152 (../lib/gtp/path.c:30)
04/11 21:50:57.275: [pfcp] INFO: pfcp_server() [10.1.59.79]:8805 (../lib/pfcp/path.c:30)
04/11 21:50:57.275: [pfcp] INFO: ogs_pfcp_connect() [10.152.183.161]:8805 (../lib/pfcp/path.c:59)
04/11 21:50:57.275: [sbi] INFO: nghttp2_server() [10.1.59.79]:7777 (../lib/sbi/nghttp2-server.c:144)
04/11 21:50:57.275: [app] INFO: SMF initialize...done (../src/smf/app.c:31)
04/11 21:50:57.276: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
04/11 21:50:57.279: [smf] INFO: [77e345b2-b9e1-41ec-bf78-4322aa4ff042] NF registred [Heartbeat:10s] (../src/smf/nf-sm.c:199)
04/11 21:50:58.755: [pfcp] INFO: ogs_pfcp_connect() [10.1.59.12]:8805 (../lib/pfcp/path.c:59)
04/11 21:50:58.755: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
04/11 21:50:59.301: [diam] INFO: CONNECTED TO 'pcrf.openverso' (SCTP,soc#22): (../lib/diameter/common/logger.c:108)

UE:
[2022-04-12 15:27:11.167] [nas] [info] UE switches to state [MM-REGISTERED/NORMAL-SERVICE]
[2022-04-12 15:27:11.167] [nas] [debug] Sending Registration Complete
[2022-04-12 15:27:11.167] [nas] [info] Initial Registration is successful
[2022-04-12 15:27:11.167] [nas] [debug] Sending PDU Session Establishment Request
[2022-04-12 15:27:11.167] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2022-04-12 15:27:11.376] [nas] [debug] Configuration Update Command received
**[2022-04-12 15:27:21.386] [nas] [error] SM forwarding failure for message type[193] with cause[PAYLOAD_NOT_FORWARDED]**
[2022-04-12 15:27:21.386] [nas] [debug] Aborting SM procedure for PTI[1], PSI[1]
[2022-04-12 15:27:22.157] [nas] [debug] Sending PDU Session Establishment Request
[2022-04-12 15:27:22.157] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]

NRF:
04/11 21:45:51.860: [nrf] WARNING: [af541f04-b9e0-41ec-88da-514d16886d4a] No heartbeat (../src/nrf/nrf-sm.c:228)

UPF:
04/11 21:50:57.275: [pfcp] INFO: ogs_pfcp_connect() [10.1.59.79]:8805 (../lib/pfcp/path.c:59)
04/11 21:50:57.276: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
04/11 21:50:58.755: [upf] WARNING: Retry to association with peer [10.152.183.178]:8805 failed (../src/upf/pfcp-sm.c:106)
04/11 21:50:58.755: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
**04/11 21:51:02.250: [pfcp] WARNING: [54974] LOCAL  No Reponse. Give up! for step 1 type 1 peer [10.1.59.8]:8805 (../lib/pfcp/xact.c:618)
04/11 21:51:02.250: [upf] WARNING: No Heartbeat from SMF [10.1.59.8]:8805 (../src/upf/pfcp-sm.c:256)**
04/11 21:51:02.250: [upf] INFO: PFCP de-associated (../src/upf/pfcp-sm.c:178)

AMF:
04/11 22:03:36.035: [gmm] INFO: UE SUPI[imsi-999700000000001] DNN[internet] S_NSSAI[SST:1 SD:0xffffff] (../src/amf/gmm-handler.c:1047)
**04/11 22:03:39.091: [sbi] WARNING: [7] Failed to connect to 10.1.59.8 port 7777: No route to host (../lib/sbi/client.c:484)
04/11 22:03:46.039: [amf] ERROR: [1:0] Cannot receive SBI message (../src/amf/amf-sm.c:584)**
04/11 22:03:46.039: [amf] WARNING: [suci-0-999-70-0000-0-0-0000000001] DL NAS transport (../src/amf/nas-path.c:573)

I'm not sure where the 10.1.59.8 address is coming from (not configured for any of the Core NFs), but according to UPF logs, it seems like it thinks that IP is for the SMF.

According to https://open5gs.org/open5gs/docs/troubleshoot/02-now-in-github-issues/, that error points to running the SMF without the NRF:

However, among these, SMF and UPF are used by both 4G EPC and 5G Core. And SMF has a protocol stack to interact with 5G NRF. Therefore, if you run SMF without running 5G NRF, the following WARNING occurs in SMF.

10/08 14:44:03.045: [sbi] WARNING: [7] Failed to connect to ::1 port 7777: Connection refused (../lib/sbi/client.c:450)
10/08 14:44:03.045: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
10/08 14:44:03.046: [diam] INFO: CONNECTED TO 'pcrf.localdomain' (SCTP,soc#16): (../lib/diameter/common/logger.c:108)
10/08 14:44:06.046: [smf] WARNING: [3c85dd06-0996-41eb-a985-476fa905aefc] Retry to registration with NRF (../src/smf/nf-sm.c:161)
10/08 14:44:06.047: [sbi] WARNING: [7] Failed to connect to ::1 port 7777: Connection refused (../lib/sbi/client.c:450)

Any ideas on why the SMF is getting assigned this .8 IP?

**Comment by avrodriguezgrad** [comment]
The resolution of IPs is through the names of the services. Could it be that you have that name mapped to an old IP?

**Comment by s-choudhury** [comment]
I haven't configured any IPs in the config files. I shouldn't have to either right? Since as you mentioned the services are resolved through the name. Other than the mcc, mnc, and slice related parameters which need to be configured for the UE and Core, all other Core services should be able to connect without config changes?

**Comment by s-choudhury** [comment]
The other components of the Core (AMF, UPF, UDM, NRF, etc) seem to establish connections just fine, so I'm wondering why the SMF is throwing a network related issue.

**Comment by avrodriguezgrad** [comment]
Can you tell me what steps you took to deploy your scenario?

**Comment by s-choudhury** [comment]
Also, when I delete the gnB pod from ueransim and it gets re-created, the SMF pod crashes:

04/21 16:42:23.161: [app] WARNING: Try to discover [PCF] (../lib/sbi/path.c:110)
04/21 16:42:23.162: [smf] INFO: [6f598526-b71d-41ec-ba25-d5811f4a0332] (NF-discover) NF registered (../src/smf/nnrf-handler.c:284)
04/21 16:42:23.162: [smf] INFO: [6f598526-b71d-41ec-ba25-d5811f4a0332] (NF-discover) NF Profile updated (../src/smf/nnrf-handler.c:330)
04/21 16:42:23.166: [smf] INFO: UE SUPI[imsi-999700000000001] DNN[internet] IPv4[10.45.0.2] IPv6[] (../src/smf/npcf-handler.c:492)
04/21 16:42:23.166: [gtp] INFO: gtp_connect() [10.1.59.12]:2152 (../lib/gtp/path.c:58)
04/21 16:42:23.167: [nas] FATAL: ogs_nas_bitrate_from_uint64: Assertion `bitrate' failed. (../lib/nas/common/types.c:433)
04/21 16:42:23.167: [core] FATAL: backtrace() returned 12 addresses (../lib/core/ogs-abort.c:37)
/usr/local/lib/x86_64-linux-gnu/libogsnas-common.so.2(ogs_nas_bitrate_from_uint64+0xdc) [0x7ffb171d3dd3]
open5gs-smfd(+0x63841) [0x55d3cb58e841]
open5gs-smfd(+0x4c801) [0x55d3cb577801]
open5gs-smfd(+0x27224) [0x55d3cb552224]
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(ogs_fsm_dispatch+0x47) [0x7ffb179e7e34]
open5gs-smfd(+0x1cda1) [0x55d3cb547da1]
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(ogs_fsm_dispatch+0x47) [0x7ffb179e7e34]
open5gs-smfd(+0xb619) [0x55d3cb536619]
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(+0x1512f) [0x7ffb179db12f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8ea7) [0x7ffb16f73ea7]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7ffb16ea3def]

Any ideas on what is causing this?

**Comment by avrodriguezgrad** [comment]
I think your problem has to be related with connectivity issues because i followed your steps and it's working for me. Which CNI are you using? 

On the other hand, SMF crash is "normal". It's reported for other users in issues of open5gs/ueransim, so i cannot do nothing there...
