### ISSUE TITLE
Exposing the AMF outside the cluster  for external access

### ISSUE THREAD

**Issue by AH-M-ED** [Gradiant/openverso-charts#56]
Hello,
Thanks for the great work here!

This is not a issue but a question related to exposing the AMF outside the cluster for external access.
What is the best way to do that and how to do it? (.yaml)

Thanks.

**Comment by AH-M-ED** [comment]
System :  Ubuntu 20.04
open5gs helm is installed in a Kubernetes cluster (k3d)

**Comment by avrodriguezgrad** [comment]
Hello,

You have two options that we have used and they work. You can configure the Kubernetes internal DNS to resolve the services you want to be externally accessible with a particular domain (<svc-name>.<namespace>.external-lab5g.gradiant.org e.g.), but you have to have an external DNS that redirects requests to the internal DNS.

The other option is to use Multus and attach an interface with an externally accessible IP.

Both options need you to configure open5gs advising one way or the other.

**Comment by AH-M-ED** [comment]
Thanks for your reply!
based on your experience,there is no need to configure a Nodeport or an Ingrees service ?
The requirement is that the amf should be reachable outside the cluster,like,from the ubuntu host machine.

Do you have any step-by-step to do the DNS configuration or a example/tuto?
Thanks.

**Comment by avrodriguezgrad** [comment]
We have not had to configure any of these types to work, so I understand that it is not necessary... but it will depend on the use case of each installation environment.

You can follow this to configure the external DNS: https://coredns.io/plugins/k8s_external/

**Comment by AH-M-ED** [comment]
Thank you,I will give it a try!
Have a good day.
