### ISSUE TITLE
NAT rule in UPF/open5gs is not working

### ISSUE THREAD

**Issue by raeyoungii** [Gradiant/openverso-charts#64]
I can see that upf has NAT rule set as default,
but there is `iptables`, `iptables-legacy` both working.

therefore, ping from ue(ueransim-gnb) to 8.8.8.8 does not work.

UPF:
`iptables -L -t nat`
```
root@open5gs-upf-0:~# iptables -L -t nat
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  10.45.0.0/16         anywhere 
```
`iptables-legacy -L -t nat`
```
root@open5gs-upf-0:~# iptables-legacy -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
```

after setting `iptables-legacy -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE`, it works.

I worder if I can put nat rule for `iptables-legacy` in helm chart so I don't need to put it manually,
or is there a way I can remove `iptables-legacy`.

Additionally, I want to know if this issue is appearing only for me.
Thanks in advance.

**Comment by avrodriguezgrad** [comment]
Hello, 

We have never had a problem with that and never got the warning when viewing the iptable. We have always had a connection on the UE using the open5gs chart and ueransim with the right configuration.

Anyway, I will try to check what could be the problem but I can't promise to have a quick answer due to workload.

Regards,

**Comment by raeyoungii** [comment]
Hi, thanks for reply.

I tested the container images for openverso/open5gs:2.4.8 (https://hub.docker.com/r/openverso/open5gs)
and ran `docker run -it --privileged openverso/open5gs:2.4.8`
this is what came out.
```
[root@centos ~]# docker run -it --privileged openverso/open5gs:2.4.8
root@a23073681492:~# iptables -L -t nat
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

I think it would be the container image problem, nothing related to helm chart.

This issue might have to go to `Gradiant/openverso-images` repo, but I'll just keep it since I think the same people are updating all the repos.

Can you check the container image and see if you can reproduce this warning?

**Comment by avrodriguezgrad** [comment]
Well, I've just run the same command as you and I don't have the warning. 
![Captura de pantalla de 2022-08-03 09-46-59](https://user-images.githubusercontent.com/91475361/182553800-88cd0bf4-10f6-4d8f-96f6-a2f26648cb1a.png)

Although, that's not the way to deploy open5gs. You can follow the next tutorial and try to test if you have the same warning deploying open5gs in Docker: https://github.com/Gradiant/openverso-images/tree/main/docs/open5gs-and-ueransim

¿Could be anything related to your host OS?

**Comment by raeyoungii** [comment]
I tested this on another vm(centos7) and it is the same.
I checked iptables version for my host OS and container image.
host's iptables:
```
[root@cent01 ~]# iptables --version
iptables v1.4.21
```

docker image iptables:
```
root@8f6bc885bc94:~# iptables --version
iptables v1.8.7 (nf_tables)
```

I can see that you're image doesn't reproduce the warning but I don't know why it is showing only to me.
If this warning show to other people, this issue should be fixed.
but for now, I think you can leave it as it is.
Thanks for your effort.
