### ISSUE TITLE
Issue in deploying openverso/oai-gnb helm chart with USRP B210

### ISSUE THREAD

**Issue by mayukhVT** [Gradiant/openverso-charts#89]
I am trying to setup Open5GS and OAI-GNodeB following the tutorial at: https://gradiant.github.io/openverso-charts/open5gs-oaignb.html . I have deployed a kubernetes cluster and to one of the nodes I have connected a USRP B210. Now I execute "helm install oai-gnb openverso/oai-gnb --version 0.3.1 --values https://gradiant.github.io/openverso-charts/docs/open5gs-oaignb/gnb-values.yaml " at the kubernetes cluster. But the oai-gnb-0 pod is in Pending state. 

The output of "kubectl describe pods oai-gnb-0" shows FailedScheduling with the following message:

"0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 Insufficient ettus.com/usrp. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims found for incoming pod."

Please let me know what may be the issue here. Please note that I have checked that the USRP is connected to the worker node (using "sudo uhd_usrp_probe" command).  @cgiraldo

**Comment by cgiraldo** [comment]
Hi,

You need a prerequisite in your k8s cluster, you need a ettus-device-plugin daemonset to manage your usrps and automatically mount them in your pods: https://github.com/Gradiant/ettus-device-plugin

We will update the tutorial to add this information.

**Comment by mayukhVT** [comment]
Thanks for your response! I figured it out later and it was working. Thanks anyway. By the way, do you have any plans of helm chart implementation of srsRAN 5G SA ? @cgiraldo

**Comment by cgiraldo** [comment]
Not for now,

We have tested srsRAN 5G SA in a local dockerized setup but It only offer 3 FDD bands that are not the ones we have licensed to operate. Maybe in the future, for sure if they finally include TDD and more bands.

But we are open for contribution if  anyone find it interesting.

Kind regards,
