### ISSUE TITLE
UPF running on separate cluster - exposing requird service for communication SMF-UPF

### ISSUE THREAD

**Issue by jmarkotic** [Gradiant/openverso-charts#91]
Hi,
currently I have UPF running on same cluster as other components. UPF is having separate data/N3 interface (same as uernasim/gNB) and communication is working fine.
I would need to separate UPF to differenet cluster since upf would be located on edge. For this i would need to expose some services as external ones via LB and explicitly define them in config files (since service autodiscovery no longer works).
For what i figured out, only services required to be external is upf-pfcp and smf-pcfp, for communication between SMF and UPF.
(port TCP 8805 on both sides).
I set static ips on LB side, so i could use those determinisitic IPs for upf-pfcf and smf-pfcp, i used in upf and smf config parts instead of K8s service name.
I tried this but didn't work. I could only find partial logs from smf that i took ( pasted below).
I will have to redo setup, but putting question up front just perhaps to get confirmation if pcfp service on both sides is the only service requred for scenario with upf separated ? and using those in config sections of upf and smf.
if i remember corrctly, system crate gtpu service as well, but that is useless since it points to ip hosted on multus interface is used.
thanks for any guideline on this.

br,
j

09/25 10:11:49.436: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
09/25 10:11:49.450: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:49.489: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:50.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:11:50.748: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:11:53.236: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:11:53.236: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:11:53.441: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:53.481: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:54.040: [pfcp] INFO: ogs_pfcp_connect() [100.96.1.1]:51209 (../lib/pfcp/path.c:61)
09/25 10:11:54.040: [smf] WARNING: cannot handle PFCP message type[1] (../src/smf/pfcp-sm.c:140)
09/25 10:11:54.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:11:54.748: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:11:56.542: [pfcp] WARNING: [2] REMOTE Request Duplicated. Discard! for step 1 type 1 peer [100.96.1.1]:51209 (../lib/pfcp/xact.c:402)
09/25 10:11:57.236: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:11:57.236: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:11:57.434: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:57.473: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:11:58.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:11:58.748: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:11:59.041: [pfcp] WARNING: [2] REMOTE Request Duplicated. Discard! for step 1 type 1 peer [100.96.1.1]:51209 (../lib/pfcp/xact.c:402)
09/25 10:12:01.236: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:12:01.236: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:12:01.426: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:01.473: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:01.540: [pfcp] WARNING: [4] LOCAL  No Reponse. Give up! for step 1 type 1 peer [100.96.1.1]:13214 (../lib/pfcp/xact.c:613)
09/25 10:12:01.540: [smf] WARNING: No Heartbeat from UPF [100.96.1.1]:13214 (../src/smf/pfcp-sm.c:304)
09/25 10:12:01.540: [smf] INFO: PFCP de-associated (../src/smf/pfcp-sm.c:179)
09/25 10:12:01.543: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
09/25 10:12:02.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:12:02.748: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:12:05.236: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:12:05.236: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:12:05.419: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:05.465: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:06.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:12:06.748: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:12:07.095: [smf] INFO: [82947024-3cba-41ed-ae42-1bbbd58b3a96] (NRF-notify) NF registered (../src/smf/nnrf-handler.c:181)
09/25 10:12:07.095: [smf] INFO: [82947024-3cba-41ed-ae42-1bbbd58b3a96] (NRF-notify) NF Profile updated (../src/smf/nnrf-handler.c:202)
09/25 10:12:07.941: [pfcp] WARNING: [5] LOCAL  No Reponse. Give up! for step 1 type 1 peer [192.168.25.25]:8805 (../lib/pfcp/xact.c:613)
09/25 10:12:07.941: [smf] WARNING: No Heartbeat from UPF [192.168.25.25]:8805 (../src/smf/pfcp-sm.c:304)
09/25 10:12:07.941: [smf] INFO: PFCP de-associated (../src/smf/pfcp-sm.c:179)
09/25 10:12:07.942: [smf] INFO: PFCP associated (../src/smf/pfcp-sm.c:174)
09/25 10:12:09.236: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)
09/25 10:12:09.236: [smf] ERROR: ogs_gtp2_parse_msg() failed (../src/smf/smf-sm.c:103)
09/25 10:12:09.410: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:09.458: [smf] ERROR: Not supported version[2] (../src/smf/pfcp-path.c:128)
09/25 10:12:10.748: [gtp] WARNING: Not implmeneted(type:110) (../lib/gtp/v2/message.c:2849)

**Comment by avrodriguezgrad** [comment]
Yes, they only need PCFP for communication being in differente clusters. Your approach is also right. When we deploy something outside, we also use Multus to give differents IPs and we change the configuration files. 

On the other hand, I've never seen these logs error so I don't think I can be useful to solve that.

**Comment by jmarkotic** [comment]
will need to redo setup to test further. i will close this now

**Comment by jmarkotic** [comment]
closing due not having proper logs for now. I will retest.
